import type { Metadata } from "next";
import { robotoCondensed, lato } from "./fonts";
import "yet-another-react-lightbox/styles.css";
import "./globals.css";
import "swiper/css/bundle";
import Header from "./header/page";
import FooterSection from "@/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${robotoCondensed.variable} ${lato.variable} antialiased`}
      >
        
        <Header />
        {children}
        <FooterSection />
      </body>
    </html>
  );
}
